const fs = require('fs');
const path = require('path');
const { AttachmentBuilder } = require('discord.js');

async function generateTranscript(channel, client) {
    const messages = await channel.messages.fetch({ limit: 100 });
    const sorted = [...messages.values()].sort((a, b) => a.createdTimestamp - b.createdTimestamp);

    let content = `
    <html>
    <head>
        <title>Ticket Transcript</title>
        <style>
            body { font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px; }
            .msg { background: white; padding: 10px; margin-bottom: 10px; border-left: 4px solid #00bfff; }
            .author { font-weight: bold; }
            .timestamp { color: #999; font-size: 12px; }
            .watermark { text-align: center; font-size: 12px; color: #888; margin-top: 20px; }
        </style>
    </head>
    <body>
        <h2>Ticket Transcript - ${channel.name}</h2>
    `;

    for (const msg of sorted) {
        content += `
        <div class="msg">
            <div class="author">${msg.author.tag}</div>
            <div class="timestamp">${new Date(msg.createdTimestamp).toLocaleString()}</div>
            <div class="content">${msg.content || '*Embed/Attachment*'}</div>
        </div>
        `;
    }

    content += `<div class="watermark">Transcript generated by GlaceYT</div></body></html>`;

    const transcriptsDir = path.join(__dirname, '../transcripts');
    const filePath = path.join(transcriptsDir, `${channel.id}.html`);

    // Ensure the transcripts directory exists
    if (!fs.existsSync(transcriptsDir)) {
        fs.mkdirSync(transcriptsDir);
    }

    fs.writeFileSync(filePath, content);

    const attachment = new AttachmentBuilder(filePath);


    return attachment;
}

module.exports = generateTranscript;
